version: "1.0"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/SHSPORTAL  # Ensure it includes all necessary files
    ports:
      - "8008:8000"   # Adjusted to match the application binding port

