# Define the application build stage
FROM python:3.11.8-slim-bookworm as app-build

# Set work directory and environment variables
WORKDIR /SHSPORTAL  
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONBUFFERED=1

# Install system dependencies
RUN apt-get update \
    && apt-get -y install netcat-openbsd gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install project dependencies
COPY requirements.txt requirements-dev.txt /SHSPORTAL/
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

# Copy project files
COPY . /SHSPORTAL

# Make the script executable
RUN ["chmod", "+x", "./run_dev.sh"]

# Command to run the application
CMD ["./run_dev.sh"]