# Define the application build stage
FROM python:3.11.8-slim-bookworm as app-build

# Set work directory and environment variables
WORKDIR /shs_webapp  # Updated to match your web app name
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONBUFFERED=1

# Install system dependencies
RUN apt-get update \
    && apt-get -y install netcat-openbsd gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install project dependencies
COPY requirements.txt requirements-dev.txt /shs_webapp/
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

# Copy project files
COPY . /shs_webapp

# Make run.sh executable
RUN ["chmod", "+x", "./run.sh"]

# Use the custom entrypoint script with Gunicorn
CMD ["./run.sh"]
