version: "1.0"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/SHSPORTAL  # Ensure it includes all necessary files
    ports:
      - "8008:8080"   # Adjusted to match the application binding port
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  litestream:
    image: litestream/litestream:0.3.13
    volumes:
      - .sqlite:///./shs_portal.db  # Adjust to match your SQLite file path
      - ./litestream.yml:/etc/litestream.yml      # Correctly map the Litestream config file
    command: ["replicate", "-config", "/etc/litestream.yml"]
  