# fly.toml app configuration file generated for shsportal on 2024-10-22T01:01:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shsportal'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "shsportal_data"
  destination = "/data"