name: CI/CD for FastAPI  # Name of your CI/CD workflow

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
jobs:
  build:  # This is the build job, it handles the installation and testing of your app
    runs-on: ubuntu-latest  # Specify the OS environment for running the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt  

    
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Deploy only if the build succeeds

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Fly.io CLI
      run: |
        curl -L https://fly.io/install.sh | sh  # This installs the Fly.io CLI

    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN:  secrets.FLY_API_TOKEN  # Use the Fly.io API token from GitHub secrets
      run: |
        flyctl auth token $FLY_API_TOKEN  
        flyctl deploy 